Manager/Models/Relevamientos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relevamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Relevamientos()
        {
            this.Alarmas = new HashSet<Alarmas>();
            this.Lecturas = new HashSet<Lecturas>();
            this.LecturasManuales = new HashSet<LecturasManuales>();
            this.Monitoreos = new HashSet<Monitoreos>();
        }
    
        public int IdRelevamiento { get; set; }
        public int IdTrampa { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Observaciones { get; set; }
        public int IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alarmas> Alarmas { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturas> Lecturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturasManuales> LecturasManuales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitoreos> Monitoreos { get; set; }
        public virtual Trampas Trampas { get; set; }
    }
}

Manager/Controllers/RelevamientosController.cs
using Manager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Text.RegularExpressions;
using Excel = Microsoft.Office.Interop.Excel;
using System.Data;

namespace Manager.Controllers
{
    
    //[Authorize(Roles = "Resp. Relevamiento")]
    public class RelevamientosController : Controller
    {
        HalconDBEntities db = new HalconDBEntities();

        // GET: Relevamientos
        [Authorize(Roles = "Resp. Relevamiento, Resp. Conteo")]
        public ActionResult Index()
        {
            return View(db.Relevamientos);
        }

        // GET: Relevamientos/Create
        [Authorize(Roles = "Resp. Relevamiento, Resp. Conteo")]
        public ActionResult Create()
        {
            ViewData["Trampas"] = new SelectList(db.Trampas.ToList(), "IdTrampa", "IdTrampa");
            ViewData["Estados"] = new SelectList(db.Estados.ToList(), "IdEstado", "Nombre");
            return View();
        }

        // POST: Relevamientos/Create
        [HttpPost]
        [Authorize(Roles = "Resp. Relevamiento, Resp. Conteo")]
        public ActionResult Create(FormCollection collection, HttpPostedFileBase ArchAuto, HttpPostedFileBase ArchManual)
        {
            try
            {
                if (ArchAuto != null &&
                    ArchAuto.ContentLength > 0 &&
                    ArchAuto.FileName.EndsWith("txt") &&
                    ArchManual != null &&
                    ArchManual.ContentLength > 0 &&
                    (ArchManual.FileName.EndsWith("xls") || ArchManual.FileName.EndsWith("xlsx"))
                    )
                {
                    string pathArchManual = "";

                    if (!Directory.Exists(Server.MapPath("Excels"))) Directory.CreateDirectory(Server.MapPath("Excels"));

                    var readerArchAuto = new BinaryReader(ArchAuto.InputStream);
                    string resultArchAuto = System.Text.Encoding.UTF8.GetString(readerArchAuto.ReadBytes(ArchAuto.ContentLength));
                    string[] lineasArchAuto = Regex.Split(resultArchAuto, "\r\n");

                    Relevamientos objRelevamiento = new Relevamientos();
                    objRelevamiento.Observaciones = collection["Observaciones"];
                    objRelevamiento.FechaCarga = DateTime.Now;
                    objRelevamiento.FechaInicio = DateTime.Parse(lineasArchAuto[0].Split(';')[0].ToString());
                    objRelevamiento.FechaFinal = DateTime.Parse(lineasArchAuto[lineasArchAuto.Length - 1].Split(';')[0].ToString());
                    objRelevamiento.IdEstado = 1;
                    objRelevamiento.IdTrampa = int.Parse(lineasArchAuto[0].Split(';')[2].ToString());
                    db.Relevamientos.Add(objRelevamiento);
                    //db.SaveChanges();

                    pathArchManual = Server.MapPath("Excels") + @"\" + ArchManual.FileName;
                    if (System.IO.File.Exists(pathArchManual)) System.IO.File.Delete(pathArchManual);

                    ArchManual.SaveAs(pathArchManual);

                    string cnnStr = "";
                    if (pathArchManual.EndsWith(".xlsx"))
                    {
                        //Excel 2007
                        cnnStr = "Provider=Microsoft.ACE.OLEDB.12.0;Extended Properties='Excel 12.0;HDR=Yes;IMEX=1'";
                        cnnStr += ";Data Source=" + pathArchManual + ";";
                    }
                    else
                    {
                        //Excel 97-2003
                        //http://www.connectionstrings.com/excel (leer sobre la clave de registro TypeGuessRows)
                        cnnStr = "Provider=Microsoft.Jet.OLEDB.4.0;Extended Properties='Excel 8.0;HDR=Yes;IMEX=1'";
                        cnnStr += ";Data Source=" + pathArchManual + ";";
                    }

                    System.Data.OleDb.OleDbConnection oCnn = new System.Data.OleDb.OleDbConnection(cnnStr);
                    System.Data.OleDb.OleDbDataAdapter oDa = null;
                    DataTable dtArchManual = new DataTable();

                    try
                    {
                        oCnn.Open();
                        //Obtenemos los nombres de las hojas del Excel.
                        DataTable dtHojas = oCnn.GetOleDbSchemaTable(System.Data.OleDb.OleDbSchemaGuid.Tables, null);
                        if (dtHojas.Rows.Count > 0)
                        {
                            string firstSheet = dtHojas.Rows[0]["TABLE_NAME"].ToString().Trim();

                            string selectCmd = "select * from [" + firstSheet + "]";
                            oDa = new System.Data.OleDb.OleDbDataAdapter(selectCmd, oCnn);
                            oDa.Fill(dtArchManual);
                        }
                        oCnn.Close();

                        dtArchManual.Columns.Add("Fecha");

                        foreach (DataRow drFila in dtArchManual.Rows)
                        {
                            int iAño = 0;
                            int iMes = 0;
                            int iDia = 0;

                            int.TryParse(drFila[0].ToString(), out iAño);
                            int.TryParse(drFila[1].ToString(), out iMes);
                            int.TryParse(drFila[2].ToString(), out iDia);

                            if (iAño > 0 && iMes > 0 && iDia > 0)
                            {
                                DateTime tFecha = new DateTime(iAño, iMes, iDia);
                                drFila["Fecha"] = tFecha.Date.ToShortDateString();
                            }

                            if (drFila["Fecha"].ToString() == objRelevamiento.FechaFinal.ToShortDateString())
                            {
                                foreach (DataColumn dcColumna in dtArchManual.Columns)
                                {
                                    if (dcColumna.Ordinal > 2)
                                    {
                                        //CORREGIR SELECCION DE INSECTO
                                        Insectos objInsecto = (from obj in db.Insectos where obj.NombreCientifico == dcColumna.ColumnName select obj).FirstOrDefault();
                                        if (objInsecto != null)
                                        {
                                            int Cantidad = 0;
                                            int.TryParse(drFila[dcColumna.Ordinal].ToString(), out Cantidad);
                                            if (Cantidad > 0)
                                            {
                                                LecturasManuales objLecturasManuales = new LecturasManuales();
                                                objLecturasManuales.IdRelevamiento = objRelevamiento.IdRelevamiento;
                                                objLecturasManuales.IdInsecto = objInsecto.IdInsecto;
                                                objLecturasManuales.Cantidad = Cantidad;
                                                objLecturasManuales.IdEstado = 1;

                                                db.LecturasManuales.Add(objLecturasManuales);
                                            }
                                        }
                                    }
                                }
                                //db.SaveChanges();
                                break;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                    finally
                    {
                        if (oCnn.State == ConnectionState.Open) oCnn.Close();
                    }

                    if (oDa != null) { oDa.Dispose(); }
                    if (oCnn != null) { oCnn.Dispose(); }








                    //var objRelevamiento2 = (from obj in db.Relevamientos select obj).OrderByDescending(i => i.IdRelevamiento).First();
                    foreach (string Linea in lineasArchAuto)
                    {
                        string[] arrDatos = Linea.Split(';');
                        if (arrDatos.Length > 1 && arrDatos[1].ToString() == "LECTURA")
                        {
                            Lecturas objLecturas = new Lecturas();
                            objLecturas.IdEstado = 1;
                            objLecturas.IdRelevamiento = objRelevamiento.IdRelevamiento;
                            objLecturas.Frecuencia = double.Parse(arrDatos[2], System.Globalization.CultureInfo.InvariantCulture);
                            objLecturas.Aleteos = int.Parse(arrDatos[3]);
                            objLecturas.FechaLectura = DateTime.Parse(arrDatos[0]);
                            db.Lecturas.Add(objLecturas);
                        }
                        else if (arrDatos.Length > 1 && arrDatos[1].ToString() == "ESTADO")
                        {
                            Monitoreos objMonitoreos = new Monitoreos();
                            objMonitoreos.IdEstado = 1;
                            objMonitoreos.IdRelevamiento = objRelevamiento.IdRelevamiento;
                            objMonitoreos.Humedad = double.Parse(arrDatos[3], System.Globalization.CultureInfo.InvariantCulture);
                            objMonitoreos.Temperatura = double.Parse(arrDatos[2], System.Globalization.CultureInfo.InvariantCulture);
                            objMonitoreos.Bateria = double.Parse(arrDatos[4], System.Globalization.CultureInfo.InvariantCulture);
                            objMonitoreos.FechaMonitoreo = DateTime.Parse(arrDatos[0]);
                            db.Monitoreos.Add(objMonitoreos);
                        }
                    }
                    db.SaveChanges();
                    return Redirect("~/Alarmas/GenerarAlarmas");

Manager/Views/Relevamientos/Create.cshtml
@model Manager.Models.Relevamientos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Relevamientos", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Relevamientos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Archivo automático", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ArchAuto" name="ArchAuto" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Archivo manual", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ArchManual" name="ArchManual" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (ViewData["Error"] != null)
        {
            <div class="form-group">
                @Html.Label("Error: ", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.Label(ViewData["Error"].ToString(), new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="~/Relevamientos/Index">Back to List</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Manager/Views/Relevamientos/Editar.cshtml
@model Manager.Models.Relevamientos

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Relevamientos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdRelevamiento)

        <div class="form-group">
            @Html.LabelFor(model => model.IdTrampa, "IdTrampa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTrampa", (SelectList)ViewData["Trampas"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTrampa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstado, "IdEstado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdEstado", (SelectList)ViewData["Estados"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="~/Relevamientos/Index">Back to List</a>
</div>

Manager/Views/Relevamientos/Index.cshtml
@model IEnumerable<Manager.Models.Relevamientos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Observaciones)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estados.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trampas.IdTrampa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Observaciones)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaFinal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estados.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trampas.IdTrampa)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IdRelevamiento }) |
            @Html.ActionLink("Validar", "Validar", new { id=item.IdRelevamiento }) |
        </td>
    </tr>
}

</table>

Manager/Views/Relevamientos/Validar.cshtml
@model Manager.Controllers.DatosParaValidar

@{
    ViewBag.Title = "Validar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Validar</h2>

<div>
    <h4>Relevamientos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Validar")
        </dt>

        <dd>
            @Html.ActionLink("Correcto", "Validar1", new { id = Model.Relevamiento.IdRelevamiento }) |
            @Html.ActionLink("Incorrecto", "Validar2", new { id = Model.Relevamiento.IdRelevamiento })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relevamiento.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relevamiento.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relevamiento.FechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relevamiento.FechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relevamiento.Observaciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relevamiento.Observaciones)
        </dd>

        <dt>
            @Html.Label("", "Estado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relevamiento.Estados.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relevamiento.Trampas.IdTrampa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relevamiento.Trampas.IdTrampa)
        </dd>

        <dt>
            @Html.Display("Gráfico")
        </dt>

        <dd>
            <div id="chart" style="width:80%; height:300px" />
        </dd>

    </dl>
</div>

@if (Model.Alarmas.Count > 0)
{
    <div>
        <table class="table">
            @*  <tr><th>@Html.Label("Alarmas") @Html.ActionLink("Regenerar", "GenerarAlarmas", "Alarmas", new { IdRelevamiento = Model.Relevamiento.IdRelevamiento }, null)</th></tr>*@

            <tr>
                <th>
                    @Html.Label("Insecto")
                    @*@Html.DisplayNameFor(model => Model.Totales.*@
                </th>
                <th>
                    @Html.Label("Cantidad maxima")
                </th>
                <th>
                    @Html.Label("Cantidad real")
                </th>
                <th>
                    @Html.Label("Tipo")
                </th>
                @*<th>
                        @Html.Label("Estado")
                    </th>

                    <th>
                        @Html.Label("Acciones")
                    </th>*@
            </tr>

            @foreach (var item in Model.Alarmas)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Insecto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadMaxima)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadReal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipo)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Estado)
                        </td>

                        <td>
                                @Html.ActionLink("Confirmar", "Confirmar", "Alarmas") |
                                @Html.ActionLink("Desestimar", "Desestimar", "Alarmas") |
                                @Html.ActionLink("Listado", "Index", "Alarmas")
                            </td>*@
                </tr>
            }

        </table>
    </div>
}

<div>
    <table class="table">
        <tr>
            <th>
                @Html.Label("Insecto")
                @*@Html.DisplayNameFor(model => Model.Totales.*@
            </th>
            <th>
                @Html.Label("Cantidad automática")
            </th>
            <th>
                @Html.Label("Cantidad manual")
            </th>
            <th>
                @Html.Label("Diferencia")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Totales)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Insecto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadAutomatica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadManual)
                </td>
                <td>
                    @Html.Label((item.CantidadAutomatica - item.CantidadManual).ToString())
                </td>
            </tr>
        }

    </table>
</div>
<p>
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="~/Relevamientos/Index">Back to List</a>
</p>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
@section scripts{
    <script>
        var chartData;
        var chartDataHour;
        var rowLevel;
        var FechaInicio;
        var FechaFinal;
        google.load("visualization", "1", { packages: ["corechart"] });

        //Load Year Wise Report On Load
        $(document).ready(function () {
            $.ajax({
                url: '/Relevamientos/InsectosDataHora',
                type: 'get',
                data: { 'idRelevamiento': @Model.Relevamiento.IdRelevamiento },
                dataType: 'json',
                success: function (d) {
                    chartDataHour = d;
                },
                error: function () {
                    alert('Error!');
                }
            }).done(function () {
                CurrentReport = 'Hora';
                generateChart(chartDataHour, "Insectos registrados");
            });
        });

        function generateChart(chartData, title) {
            var data = google.visualization.arrayToDataTable(chartData);

            var options = {
                title: title,
                pointSize: 5,
                focusTarget: "category",
                hAxis: { showTextEvery: 1 }
            }

            var lineChart = new google.visualization.LineChart(document.getElementById('chart'));
            lineChart.draw(data, options);
        }


    </script>
}